#!/usr/bin/env python3
"""
Email Setup Script for PM Internship Recommender
This script helps you configure email settings for OTP sending.
"""

import os

def setup_email_config():
    print("🔧 Email Configuration Setup")
    print("=" * 50)
    
    print("\n📧 Choose your email provider:")
    print("1. Gmail (Recommended)")
    print("2. Outlook/Hotmail")
    print("3. Yahoo")
    print("4. Custom SMTP")
    
    choice = input("\nEnter your choice (1-4): ").strip()
    
    if choice == "1":
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        provider = "Gmail"
    elif choice == "2":
        smtp_server = "smtp-mail.outlook.com"
        smtp_port = 587
        provider = "Outlook"
    elif choice == "3":
        smtp_server = "smtp.mail.yahoo.com"
        smtp_port = 587
        provider = "Yahoo"
    elif choice == "4":
        smtp_server = input("Enter SMTP server: ").strip()
        smtp_port = int(input("Enter SMTP port (usually 587): ").strip())
        provider = "Custom"
    else:
        print("❌ Invalid choice. Using Gmail as default.")
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        provider = "Gmail"
    
    print(f"\n✅ Using {provider} configuration")
    
    # Get email credentials
    sender_email = input(f"\n📧 Enter your {provider} email address: ").strip()
    sender_password = input(f"🔑 Enter your {provider} password or app password: ").strip()
    sender_name = input("👤 Enter sender name (default: PM Internship Recommender): ").strip() or "PM Internship Recommender"
    
    # Create email configuration
    config_content = f'''# Email Configuration
# Generated by setup_email.py

EMAIL_CONFIG = {{
    'smtp_server': '{smtp_server}',
    'smtp_port': {smtp_port},
    'sender_email': '{sender_email}',
    'sender_password': '{sender_password}',
    'sender_name': '{sender_name}'
}}

# Instructions for {provider}:
'''
    
    if provider == "Gmail":
        config_content += '''# 1. Enable 2-factor authentication on your Gmail account
# 2. Generate an App Password: https://myaccount.google.com/apppasswords
# 3. Use the App Password (not your regular password) in sender_password
# 4. Make sure "Less secure app access" is disabled (use App Passwords instead)
'''
    elif provider == "Outlook":
        config_content += '''# 1. Enable 2-factor authentication on your Outlook account
# 2. Generate an App Password: https://account.microsoft.com/security
# 3. Use the App Password (not your regular password) in sender_password
'''
    elif provider == "Yahoo":
        config_content += '''# 1. Enable 2-factor authentication on your Yahoo account
# 2. Generate an App Password: https://login.yahoo.com/account/security
# 3. Use the App Password (not your regular password) in sender_password
'''
    else:
        config_content += f'''# Configure your custom SMTP server settings
# Make sure your SMTP server supports TLS/SSL
'''
    
    # Write configuration file
    with open('email_config.py', 'w') as f:
        f.write(config_content)
    
    print(f"\n✅ Email configuration saved to email_config.py")
    print(f"📧 SMTP Server: {smtp_server}:{smtp_port}")
    print(f"📧 Sender Email: {sender_email}")
    print(f"👤 Sender Name: {sender_name}")
    
    print(f"\n🚀 You can now start the server with: python app.py")
    print(f"📝 OTP emails will be sent from: {sender_email}")
    
    if provider == "Gmail":
        print(f"\n⚠️  Important for Gmail users:")
        print(f"   1. Enable 2-factor authentication")
        print(f"   2. Generate an App Password: https://myaccount.google.com/apppasswords")
        print(f"   3. Use the App Password (not your regular password)")

if __name__ == "__main__":
    setup_email_config()
